# Generated by Django 3.2 on 2022-08-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_remove_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default=0, max_length=250, unique=True, unique_for_date='published'),
            preserve_default=False,
        ),
    ]
