# Generated by Django 3.2 on 2022-08-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_alter_noticia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='slug',
        ),
    ]
