# Generated by Django 3.2 on 2022-08-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_remove_noticia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
