# Generated by Django 3.2 on 2022-08-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Evento')),
                ('description', models.TextField()),
            ],
        ),
    ]
