# Generated by Django 3.2 on 2022-08-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='modalidad',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='eventos.modalidad'),
            preserve_default=False,
        ),
    ]
