# Generated by Django 3.2 on 2022-08-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20220827_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='eventos.estado'),
            preserve_default=False,
        ),
    ]
