# Generated by Django 3.2 on 2022-08-27 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20220827_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_carga',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
