# Generated by Django 3.2 on 2022-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso_imagen', models.ImageField(blank=True, null=True, upload_to='galeria')),
            ],
        ),
    ]
