# Generated by Django 3.2 on 2022-08-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
