# Generated by Django 3.2 on 2022-08-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_integrante', models.CharField(max_length=80)),
                ('recurso_foto', models.ImageField(blank=True, null=True, upload_to='contacto')),
            ],
        ),
    ]
