# Generated by Django 3.2 on 2022-08-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='url_insta',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
