# Generated by Django 3.2 on 2022-08-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_contacto_url_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre_integrante',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='url_insta',
            field=models.URLField(blank=True, null=True),
        ),
    ]
